# JWT Configuration
jwt.secret=${JWT_SECRET}

# Server
server.port=8082

# Configuración SQS
entrypoint.sqs.region= ${AWS_REGION}
entrypoint.sqs.queueUrl= ${AWS_QUEUE_REPORTS_URL}

entrypoint.sqs.waitTimeSeconds= 20
entrypoint.sqs.maxNumberOfMessages= 10
entrypoint.sqs.visibilityTimeoutSeconds= 10
entrypoint.sqs.numberOfThreads= 1